### ISSUE TITLE
lambda2 in SSME and SSMEI

### ISSUE THREAD

**Issue by rueuntal** [ajrominger/MaxEntSuffStat#1]
Hi Andy - I just realized that lambda2 in SSME and SSMEI might actually be different. If you look at Eqn 13, lambda2 in SSME = 1/M-bar = S / M, while in Eqn 17 lambda2 in SSMEI = n-bar/M-bar = (N/S) / (M/S) = N / M. What do you think?

**Comment by ajrominger** [comment]
Hi Xiao!  I'm just finally getting to this.  Did you resolve this in your code too?

**Comment by rueuntal** [comment]
Hi Andy - I did, or at least so I think :) I used the wrong lambda2 for SSMEI in the previous result, but found out the error through the safety check that the difference in likelihoods between SSMEI and SSNTI should be entirely due to the SADs.

**Comment by ajrominger** [comment]
fixed here too!  thanks!
